version: '3.8'

services:
  bot:
    container_name: bot
    build:
      context: .
    ports:
    - 3000:3000
    - 9229:9229
    volumes:
    - ./:/app
    - /app/node_modules
    restart: unless-stopped
    command: npm run start:debug