version: '3.8'

services:
  bot:
    container_name: bot
    build:
      context: .
    ports:
    - 3000:3000
    - 9229:9229
    volumes:
    - ./:/app
    - /app/node_modules
    restart: unless-stopped
    environment:
      - FETCH_INTERVAL=*/5 * * * * *
      - CURRENCY_PAIRS=BTC-USD,ETH-USD,LTC-USD
      - PRICE_OSCILLATION_PERCENTAGE=0.01
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alerts
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres